# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1233, 715)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 7150000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_left = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_left.sizePolicy().hasHeightForWidth())
        self.pushButton_left.setSizePolicy(sizePolicy)
        self.pushButton_left.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_left.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_left.setIcon(icon)
        self.pushButton_left.setObjectName("pushButton_left")
        self.horizontalLayout.addWidget(self.pushButton_left)
        self.label_imageIndx = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_imageIndx.setFont(font)
        self.label_imageIndx.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imageIndx.setObjectName("label_imageIndx")
        self.horizontalLayout.addWidget(self.label_imageIndx)
        self.pushButton_right = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_right.sizePolicy().hasHeightForWidth())
        self.pushButton_right.setSizePolicy(sizePolicy)
        self.pushButton_right.setBaseSize(QtCore.QSize(50, 50))
        self.pushButton_right.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_right.setIcon(icon1)
        self.pushButton_right.setObjectName("pushButton_right")
        self.horizontalLayout.addWidget(self.pushButton_right)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 905, 611))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_image = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_image.setFont(font)
        self.label_image.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image.setLineWidth(2)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.gridLayout_2.addWidget(self.label_image, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 31, 281, 176))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_result_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_result_1.setFont(font)
        self.label_result_1.setObjectName("label_result_1")
        self.gridLayout.addWidget(self.label_result_1, 0, 0, 1, 1)
        self.progressBar_1 = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.progressBar_1.setFont(font)
        self.progressBar_1.setProperty("value", 24)
        self.progressBar_1.setObjectName("progressBar_1")
        self.gridLayout.addWidget(self.progressBar_1, 0, 1, 1, 1)
        self.label_result_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_result_2.setFont(font)
        self.label_result_2.setObjectName("label_result_2")
        self.gridLayout.addWidget(self.label_result_2, 1, 0, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 1, 1, 1, 1)
        self.label_result_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_result_3.setFont(font)
        self.label_result_3.setObjectName("label_result_3")
        self.gridLayout.addWidget(self.label_result_3, 2, 0, 1, 1)
        self.progressBar_3 = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.progressBar_3.setFont(font)
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout.addWidget(self.progressBar_3, 2, 1, 1, 1)
        self.label_result_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_result_4.setFont(font)
        self.label_result_4.setObjectName("label_result_4")
        self.gridLayout.addWidget(self.label_result_4, 3, 0, 1, 1)
        self.progressBar_4 = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.progressBar_4.setFont(font)
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setObjectName("progressBar_4")
        self.gridLayout.addWidget(self.progressBar_4, 3, 1, 1, 1)
        self.label_result_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_result_5.setFont(font)
        self.label_result_5.setObjectName("label_result_5")
        self.gridLayout.addWidget(self.label_result_5, 4, 0, 1, 1)
        self.progressBar_5 = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.progressBar_5.setFont(font)
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setObjectName("progressBar_5")
        self.gridLayout.addWidget(self.progressBar_5, 4, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1233, 25))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuModel = QtWidgets.QMenu(self.menubar)
        self.menuModel.setObjectName("menuModel")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionZoom_25 = QtWidgets.QAction(MainWindow)
        self.actionZoom_25.setObjectName("actionZoom_25")
        self.actionZoom_Out_25 = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out_25.setObjectName("actionZoom_Out_25")
        self.actionNormal_Size = QtWidgets.QAction(MainWindow)
        self.actionNormal_Size.setObjectName("actionNormal_Size")
        self.actionFit_to_Window = QtWidgets.QAction(MainWindow)
        self.actionFit_to_Window.setObjectName("actionFit_to_Window")
        self.actionVGG = QtWidgets.QAction(MainWindow)
        self.actionVGG.setObjectName("actionVGG")
        self.actionInception = QtWidgets.QAction(MainWindow)
        self.actionInception.setObjectName("actionInception")
        self.actionResNet = QtWidgets.QAction(MainWindow)
        self.actionResNet.setObjectName("actionResNet")
        self.actionMobileNet = QtWidgets.QAction(MainWindow)
        self.actionMobileNet.setObjectName("actionMobileNet")
        self.actionShuffleNet = QtWidgets.QAction(MainWindow)
        self.actionShuffleNet.setObjectName("actionShuffleNet")
        self.actionResNeXt = QtWidgets.QAction(MainWindow)
        self.actionResNeXt.setObjectName("actionResNeXt")
        self.actionShuffleNet_2 = QtWidgets.QAction(MainWindow)
        self.actionShuffleNet_2.setObjectName("actionShuffleNet_2")
        self.actionDPN = QtWidgets.QAction(MainWindow)
        self.actionDPN.setObjectName("actionDPN")
        self.menuFIle.addAction(self.actionOpen)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionExit)
        self.menuView.addAction(self.actionZoom_25)
        self.menuView.addAction(self.actionZoom_Out_25)
        self.menuView.addAction(self.actionNormal_Size)
        self.menuView.addAction(self.actionFit_to_Window)
        self.menuModel.addAction(self.actionVGG)
        self.menuModel.addAction(self.actionInception)
        self.menuModel.addAction(self.actionResNet)
        self.menuModel.addAction(self.actionMobileNet)
        self.menuModel.addAction(self.actionShuffleNet)
        self.menuModel.addAction(self.actionResNeXt)
        self.menuModel.addAction(self.actionShuffleNet_2)
        self.menuModel.addAction(self.actionDPN)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuModel.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scene Recognition"))
        self.label_imageIndx.setText(_translate("MainWindow", "0/0"))
        self.label_image.setText(_translate("MainWindow", "Image"))
        self.groupBox.setTitle(_translate("MainWindow", "Results"))
        self.label_result_1.setText(_translate("MainWindow", "label1:"))
        self.label_result_2.setText(_translate("MainWindow", "label2:"))
        self.label_result_3.setText(_translate("MainWindow", "label3:"))
        self.label_result_4.setText(_translate("MainWindow", "label4:"))
        self.label_result_5.setText(_translate("MainWindow", "label5:"))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuModel.setTitle(_translate("MainWindow", "Models"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionZoom_25.setText(_translate("MainWindow", "Zoom In(25%)"))
        self.actionZoom_Out_25.setText(_translate("MainWindow", "Zoom Out(25%)"))
        self.actionNormal_Size.setText(_translate("MainWindow", "Normal Size"))
        self.actionFit_to_Window.setText(_translate("MainWindow", "Fit to Window"))
        self.actionVGG.setText(_translate("MainWindow", "VGG"))
        self.actionInception.setText(_translate("MainWindow", "Inception"))
        self.actionResNet.setText(_translate("MainWindow", "ResNet"))
        self.actionMobileNet.setText(_translate("MainWindow", "MobileNet"))
        self.actionShuffleNet.setText(_translate("MainWindow", "Xception"))
        self.actionResNeXt.setText(_translate("MainWindow", "ResNeXt"))
        self.actionShuffleNet_2.setText(_translate("MainWindow", "ShuffleNet"))
        self.actionDPN.setText(_translate("MainWindow", "DPN"))

